debug = true

[cookies]
http_only = false
secure = false

[database]
database = "cardbox"
host = "localhost"
password = "cardbox"
user = "cardbox"
pool_size = 2
openssl_validate = false

[server]
host = "localhost"
port = 9110

[accesso]
public_url = "http://localhost:9115"
internal_url = "http://localhost:9110"
client_id = '00000000-0000-4000-acce-000000009100'
redirect_back_url = "http://localhost:9100/accesso/done"
client_secret = "CardboxDev"
ssl_validate = false
