[package]
name = "cardbox-db"
version = "0.1.0"
authors = ["Sergey Sova <mail@sergeysova.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.5", features = [
  "postgres",
  "uuidv07",
  "chrono",
  "r2d2",
  "serde_json"
] }
serde = "1.0.115"
serde_json = "1.0.57"
chrono = { version = "0.4.13", features = ["serde"] }
