[package]
authors = ["Sergey Sova <mail@sergeysova.com>"]
edition = "2018"
name = "cardbox-db"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.40"
cardbox-core = {path = "../core"}
chrono = {version = "0.4.13", features = ["serde"]}
diesel = {version = "1.4.5", features = [
  "postgres",
  "uuidv07",
  "chrono",
  "r2d2",
  "serde_json",
]}
log = "0.4.11"
serde = "1.0.115"
serde_json = "1.0.57"
uuid = {version = "0.8.1", features = ["serde", "v4"]}
r2d2 = "0.8.9"
