[package]
authors = ["Sergey Sova <mail@sergeysova.com>"]
edition = "2018"
name = "cardbox-api-internal"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "1.1.1"
actix-web = "2.0.0"
cardbox-logic = {path = "../logic"}
chrono = {version = "0.4.15", features = ["serde"]}
diesel = {version = "1.4.5", features = [
  "postgres",
  "uuidv07",
  "chrono",
  "r2d2",
  "serde_json",
]}
dotenv = "0.15.0"
env_logger = "0.7.1"
lazy_static = "1.4.0"
log = "0.4.11"
pretty_env_logger = "0.4.0"
r2d2 = "0.8.9"
serde = {version = "1.0.115", features = ["derive"]}
serde_json = "1.0.57"
serde_plain = "0.3.0"
uuid = {version = "0.8.1", features = ["serde", "v4"]}
actix-swagger = "0.2.1"
url = "2.1.1"
