[package]
name = "api-internal"
version = "0.1.0"
authors = ["Sergey Sova <s.sova@redmadrobot.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
