[package]
authors = ["Sergey Sova <mail@sergeysova.com>"]
edition = "2018"
name = "cardbox-api-internal"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "2.2.0"
actix-swagger = "0.3.0"
actix-web = "4.0.0-beta.6"
actix-http = "3.0.0-beta.6"
async-trait = "0.1.50"
awc = { version = "3.0.0-beta.5", features = ["compress", "openssl"] }
cardbox-core = { path = "../core" }
cardbox-db = { path = "../db" }
cardbox-generator = { path = "../generator" }
chrono = { version = "0.4.19", features = ["serde"] }
dotenv = "0.15.0"
once_cell = "1.7.2"
log = "0.4.14"
openssl = "0.10.34"
pretty_env_logger = "0.4.0"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
serde_plain = "0.3.0"
time = "0.2.26"
tokio = { version = "1.6.0", features = ["sync"] }
url = "2.2.2"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
