name: StartTools Docker Image CI

on:
  push:
    branches:
      - master
      - dev
    paths:
      - "start-tools.Dockerfile"
      - ".github/workflows/image-start-tools.yml"

jobs:
  image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@2.12
        with:
          name: cardboxdev/backend/start-tools
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: start-tools.Dockerfile
          tags: "1.1"
