name: Builder Image CI

on:
  push:
    branches:
      - master
      - dev
    paths:
      - "builder.Dockerfile"
      - ".github/workflows/image-builder.yml"

jobs:
  image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@2.12
        with:
          name: cardboxdev/backend/builder
          username: sergeysova
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: builder.Dockerfile
          tags: "1.45.2"
