name: API Docker Image CI

on:
  push:
    branches:
      - master
      - dev
    paths:
      - ".github/workflows/image-api.yml"
      - "db/**"
      - "logic/**"
      - "migrations/**"
      - "api-admin/**"
      - "api-internal/**"
      - "api-private/**"
      - "api-public/**"
      - "docker-entrypoint.sh"
      - "Dockerfile"
      - "Cargo.lock"
    tags:
      - "api-admin@*"
      - "api-internal@*"
      - "api-private@*"
      - "api-public@*"

jobs:
  api-image:
    strategy:
      matrix:
        api: [admin, internal, private, public]

    name: api-${{ matrix.api }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Publish Docker
        uses: sergeysova/docker-publish-action@v1
        with:
          image: cardboxdev/backend/api-${{ matrix.api }}
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          buildargs: CRATE_NAME=api-${{ matrix.api }}
          snapshot: "true"
          tag_semver: skip
          tag_separator: "@"
          semver_higher: "true"

      - name: Trigger deploy to Dev
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TRIGGER_DEPLOY_TOKEN }}
          repository: cardboxdev/releases
          event-type: deploy-dev
          client-payload: '{"github": ${{ toJson(github) }}}'
